name: Rebel watcher (cron, artifacts state)

on:
  schedule:
    - cron: "2 * * * *"   # co godzinę; zmień na */15 * * * * jeśli chcesz co 15 min
  workflow_dispatch: {}

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: (debug) show current path and files
        run: |
          pwd
          ls -la

      - name: Download previous state artifact (if exists)
        uses: dawidd6/action-download-artifact@v9
        with:
          workflow: rebel.yml
          name: rebel-state
          path: .
          if_no_artifact_found: ignore

      - name: Ensure default state file exists
        run: |
          if [ ! -f "rebel_uszkodzone_seen.json" ]; then
            echo '{"seen_ids": [], "last_check": null}' > rebel_uszkodzone_seen.json
          fi

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          pip install --no-cache-dir requests beautifulsoup4

      - name: Run watcher
        env:
          REBEL_STATE_FILE: rebel_uszkodzone_seen.json
        run: |
          python rebel_uszko.py

      - name: Upload state artifact
        uses: actions/upload-artifact@v4
        with:
          name: rebel-state
          path: rebel_uszkodzone_seen.json
          retention-days: 90
